export default [
  {
    product: 'Pavakka Chips',
    qty: '200 GM',
    mrp: '115.00',
    pkd_dt: '02-11-2022',
    batchNo: '224202',
    id: '123456789123456',
    nutritionFacts: {
      calories: '487 cal',
      totalFat: '21 g',
      protein: '4 g',
      cholesterol: '0 mg',
      carbohydrate: '45 g',
    },
    ing: [
      'Rice Flour, ',
      'Gram Flour, ',
      'Chilly Powder, ',
      'Jeerakam, ',
      'Kayam, ',
      'Pepper, ',
      'Salt, ',
    ],
  },
  {
    product: 'Thatta',
    qty: '200 GM',
    mrp: '115.00',
    pkd_dt: '02-11-2022',
    batchNo: '224202',
    id: '12345678911223456',
    nutritionFacts: {
      calories: '487 cal',
      totalFat: '21 g',
      protein: '4 g',
      cholesterol: '0 mg',
      carbohydrate: '45 g',
    },
    ing: [
      'Rice Flour, ',
      'Gram Flour, ',
      'Chilly Powder, ',
      'Jeerakam, ',
      'Kayam, ',
      'Pepper, ',
      'Salt, ',
    ],
  },
  {
    product: 'Achappam',
    qty: '10 NOS',
    mrp: '95.00',
    pkd_dt: '02-11-2022',
    batchNo: '224202',
    id: '1234567891223456',
    nutritionFacts: {
      calories: '487 cal',
      totalFat: '21 g',
      protein: '4 g',
      cholesterol: '0 mg',
      carbohydrate: '45 g',
    },
    ing: [
      'Rice Flour, ',
      'Gram Flour, ',
      'Chilly Powder, ',
      'Jeerakam, ',
      'Kayam, ',
      'Pepper, ',
      'Salt, ',
    ],
  },
  {
    product: 'Chembu chips',
    qty: '200 GM',
    mrp: '130.00',
    pkd_dt: '02-11-2022',
    batchNo: '224202',
    id: '12345678912233456',
    nutritionFacts: {
      calories: '487 cal',
      totalFat: '21 g',
      protein: '4 g',
      cholesterol: '0 mg',
      carbohydrate: '45 g',
    },
    ing: [
      'Rice Flour, ',
      'Gram Flour, ',
      'Chilly Powder, ',
      'Jeerakam, ',
      'Kayam, ',
      'Pepper, ',
      'Salt, ',
    ],
  },
];
    

