export default {
  DROP_DOWN_ARROW: require('../assets/images/drop-down-arrow.png'),
  RADIO_BUTTON_ON: require('../assets/images/radio.png'),
  RADIO_BUTTON: require('../assets/images/radio-button.png'),
  STICKER_LOG: require('../assets/images/sree_nand_1200x480.jpg'),
  FSSAI_ICON: require('../assets/images/jjjj.png'),
  BLUETOOTH_ICON: require('../assets/images/bluetooth.png'),
  EYE_OPEN: require('../assets/images/view.png'),
  EYE_CLOSE: require('../assets/images/hidden.png'),
  MENU: require('../assets/images/menu.png'),
  BACK_ARROW: require('../assets/images/back.png'),
  PHONE: require('../assets/images/phone-call.png'),
  EMAIL: require('../assets/images/email.png'),
  EDIT: require('../assets/images/edit.png'),
  DELETE: require('../assets/images/delete.png'),
  CLOSE: require('../assets/images/close.png'),
  PLUS: require('../assets/images/plus.png'),
  SPLASHSCREEN: require('../assets/images/splash.webp'),
  LOGO: require('../assets/images/print.png'),
};
